image: atlassian/default-image:2

pipelines:
  pull-requests:
    "**":
      - step:
          max-time: 120
          size: 1x
          script:
            - npm test
          trigger: automatic

  branches:
    main:
      - step:
          name: Build
          caches:
            - node
          deployment: Test
          script:
            - apt-get update
            - apt-get install -y zip
            - zip -r application.zip .
          artifacts:
            - application.zip

      - step:
          name: Upload to S3
          script:
            # Test upload
            - pipe: atlassian/aws-code-deploy:0.2.10
              variables:
                AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
                AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
                AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
                COMMAND: 'upload'
                APPLICATION_NAME: ${APPLICATION_NAME}
                ZIP_FILE: 'application.zip'
                S3_BUCKET: ${S3_BUCKET}

      - step:
          name: Deploy with CodeDeploy
          script:
            # Test upload
            - pipe: atlassian/aws-code-deploy:0.2.10
              variables:
                AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
                AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
                AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
                COMMAND: 'deploy'
                APPLICATION_NAME: ${APPLICATION_NAME}
                DEPLOYMENT_GROUP: ${DEPLOYMENT_GROUP}
                S3_BUCKET: ${S3_BUCKET}
                IGNORE_APPLICATION_STOP_FAILURES: 'true'
                FILE_EXISTS_BEHAVIOR: 'OVERWRITE'
                WAIT: 'true' 


